### ISSUE TITLE
code should be properly formated

### ISSUE THREAD

**Issue by alejo4373** [camunity/gitABCs#10]
I suggest line 7 of readme instead of just plain git clone https://github.com/kevina101/gitABCs.git should be formatted like ```git clone https://github.com/kevina101/gitABCs.git``` @kevina101 can you work on this? Thanks bro!

**Comment by kevina101** [comment]
yes @alejo4373  I can work on that

**Comment by kevina101** [comment]
I fixed the issue.

**Comment by camunity** [comment]
yassssss @alejo4373 thanks for this thought. I definitely agree. @kevina101 let me know if you need any help!
